#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import config
import os
from dsrLogger import logger as log

config = config.Config()

def create_crond_file() -> None:
    """
    Creating cron job file in /etc/cron.d
    :return:
    """
    try:
        int(config.CRON_IPSET_UPDATE_INTERVAl)
    except ValueError as err:
        log.critical(err)
        log.critical("Check CRON_IPSET_UPDATE_INTERVAl option in config file!")
        raise SystemExit
    if config.CRON_IPSET_UPDATE_INTERVAl > 0:
        with open(config.CRON_FILE, 'w') as cr:
            cr.write(
                "# Do not edit this file manually!\n"
                "# Change CRON_IPSET_UPDATE_INTERVAl option in amnezia_postinstall config file and run script instead.\n"
                "SHELL=/bin/sh\n"
                "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n"
                "# Update ipset country lists\n"
                "23 3 */" + str(config.CRON_IPSET_UPDATE_INTERVAl) + " * * root cd " + config.MAIN_DIR +
                " && /usr/bin/python3 " + config.MAIN_DIR + "/ipset_cron.py &>/dev/null\n"
            )
    else:
        log.critical("Update interval must be > 0! Check CRON_IPSET_UPDATE_INTERVAl option in config file!")


def crond_file_exist() -> bool:
    """
    Checking if cron file already exist
    :return:    True or False
    """
    return os.path.isfile(config.CRON_FILE)


def current_crond_interval() -> bool or int:
    """
    :return: Current update interval in days or False if any error
    """
    current_interval = False
    cron_file = config.CRON_FILE
    try:
        with open(cron_file, 'r') as cf:
            for line in cf:
                if "ipset_cron.py" in line:
                    parts = line.split('root')
                    current_interval = parts[0].split("/")
                    current_interval = current_interval[1].replace("*", "").rstrip()
                    return int(current_interval)
    except TypeError as err:
        log.error(err)
        return False
    except ValueError as err:
        log.error(err)
        return False
    return  current_interval


def configure_crond():
    """
    Inserting or updating crond file in /etc/cron.d if it enabled in config file (CREATE_IPSET_CRON_SCHEDULE)
    Removing if CREATE_IPSET_CRON_SCHEDULE is False
    :return:
    """
    if config.CREATE_IPSET_CRON_SCHEDULE is True:
        log.info("Checking cron.d file ...")
        if crond_file_exist() is True:
            interval = current_crond_interval()
            if interval is not False:
                if interval != config.CRON_IPSET_UPDATE_INTERVAl:
                    log.info("Changing ipset lists update interval to every " + str(config.CRON_IPSET_UPDATE_INTERVAl) +
                             " days")
                    create_crond_file()
        else:
            log.info("Creating cron file...")
            create_crond_file()
        log.info("cron.d file looks good!")
    else:
        if crond_file_exist() is True:
            log.info("Cron job disabled in config file. Removing file " + config.CRON_FILE)
            os.remove(config.CRON_FILE)


if __name__ == '__main__':
    configure_crond()
